services:
  go:
    build:
      context: '.'
      dockerfile: /docker/1.25.6/Dockerfile
    image: 'go-1.25.6/app'
    volumes:
      - '.:/usr/src/app'
    networks:
      - go
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:18.1-trixie'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'go-pgsql:/var/lib/postgresql'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - go
    healthcheck:
      test: [ CMD, pg_isready, '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}' ]
      retries: 3
      timeout: 5s
networks:
  go:
    driver: bridge
volumes:
  go-pgsql:
    driver: local
